{"uid":"70362a9d04d7d08f","name":"Administrador acessa a aplicação operações módulo Comercial","fullName":"Gerenciamento de Perfis de Acesso: Administrador acessa a aplicação operações módulo Comercial","historyId":"c7c555087dacf0c257a9aff9de33ca23","time":{"start":1744137855928,"stop":1744137856027,"duration":99},"status":"broken","statusMessage":"AttributeError: 'Context' object has no attribute 'perfil_page'\n","statusTrace":"  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\test_perfil_de_acesso_steps.py\", line 8, in step_then_acesso_total\n    assert context.perfil_page.possui_acesso_total(), \"Usuário não possui acesso total ao sistema.\"\n           ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\venv\\Lib\\site-packages\\behave\\runner.py\", line 321, in __getattr__\n    raise AttributeError(msg)\n","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"AttributeError: 'Context' object has no attribute 'perfil_page'\n","statusTrace":"  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\test_perfil_de_acesso_steps.py\", line 8, in step_then_acesso_total\n    assert context.perfil_page.possui_acesso_total(), \"Usuário não possui acesso total ao sistema.\"\n           ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\venv\\Lib\\site-packages\\behave\\runner.py\", line 321, in __getattr__\n    raise AttributeError(msg)\n","steps":[{"name":"Given que o usuário está logado como \"Administrador\"","time":{"start":1744137855942,"stop":1744137855989,"duration":47},"status":"passed","steps":[{"name":"Validando que o usuário está logado como Administrador","time":{"start":1744137855947,"stop":1744137855989,"duration":42},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"context","value":"<behave.runner.Context object at 0x000001DD352381A0>"}],"hasContent":true,"attachmentsCount":0,"shouldDisplayMessage":false,"attachmentStep":false,"stepsCount":0}],"attachments":[],"parameters":[],"hasContent":true,"attachmentsCount":0,"shouldDisplayMessage":false,"attachmentStep":false,"stepsCount":1},{"name":"Then eu devo ter acesso total ao sistema","time":{"start":1744137855989,"stop":1744137856016,"duration":27},"status":"broken","statusMessage":"AttributeError: 'Context' object has no attribute 'perfil_page'\n","statusTrace":"  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\test_perfil_de_acesso_steps.py\", line 8, in step_then_acesso_total\n    assert context.perfil_page.possui_acesso_total(), \"Usuário não possui acesso total ao sistema.\"\n           ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\venv\\Lib\\site-packages\\behave\\runner.py\", line 321, in __getattr__\n    raise AttributeError(msg)\n","steps":[],"attachments":[],"parameters":[],"hasContent":true,"attachmentsCount":0,"shouldDisplayMessage":true,"attachmentStep":false,"stepsCount":0},{"name":"And eu devo conseguir realizar todas as operações do módulo Comercial","time":{"start":1744137856027,"stop":1744137856027,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"hasContent":false,"attachmentsCount":0,"shouldDisplayMessage":false,"attachmentStep":false,"stepsCount":0}],"attachments":[],"parameters":[],"hasContent":true,"attachmentsCount":0,"shouldDisplayMessage":false,"attachmentStep":false,"stepsCount":4},"afterStages":[],"labels":[{"name":"severity","value":"normal"},{"name":"feature","value":"Gerenciamento de Perfis de Acesso"},{"name":"framework","value":"behave"},{"name":"language","value":"cpython3"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"70362a9d04d7d08f.json","parameterValues":[]}