{"name": "Cancelar exclusão de um usuário", "status": "failed", "statusDetails": {"message": "AssertionError: Elemento de validação de Administrador não encontrado.\n", "trace": "  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"features\\steps\\test_tela_de_usuarios_steps.py\", line 20, in validar_usuario_administrador\n    context.tela_de_usuarios_page.validar_usuario_administrador()\n  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\neo_liberalizados-automacao\\features\\pages\\tela_de_usuarios_pages.py\", line 48, in validar_usuario_administrador\n    raise AssertionError(\"Elemento de validação de Administrador não encontrado.\")\n"}, "steps": [{"name": "Given que o usuário está logado como \"Administrador\"", "status": "failed", "statusDetails": {"message": "AssertionError: Elemento de validação de Administrador não encontrado.\n", "trace": "  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"features\\steps\\test_tela_de_usuarios_steps.py\", line 20, in validar_usuario_administrador\n    context.tela_de_usuarios_page.validar_usuario_administrador()\n  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\neo_liberalizados-automacao\\features\\pages\\tela_de_usuarios_pages.py\", line 48, in validar_usuario_administrador\n    raise AssertionError(\"Elemento de validação de Administrador não encontrado.\")\n"}, "steps": [{"name": "Validando que o usuário está logado como Administrador", "status": "failed", "statusDetails": {"message": "AssertionError: Elemento de validação de Administrador não encontrado.\n", "trace": "  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"features\\steps\\test_tela_de_usuarios_steps.py\", line 20, in validar_usuario_administrador\n    context.tela_de_usuarios_page.validar_usuario_administrador()\n  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\neo_liberalizados-automacao\\features\\pages\\tela_de_usuarios_pages.py\", line 48, in validar_usuario_administrador\n    raise AssertionError(\"Elemento de validação de Administrador não encontrado.\")\n"}, "parameters": [{"name": "context", "value": "<behave.runner.Context object at 0x0000024CD3BD42C0>"}], "start": 1743784796351, "stop": 1743784796427}], "start": 1743784796351, "stop": 1743784796427}, {"name": "When navega até a tela de usuários - Perfil", "status": "skipped", "start": 1743784796436, "stop": 1743784796436}, {"name": "When pesquisa um usuario cadastrado", "status": "skipped", "start": 1743784796436, "stop": 1743784796436}, {"name": "When clica em excluir e cancela a exclusao", "status": "skipped", "start": 1743784796436, "stop": 1743784796436}, {"name": "Then navega até a tela de usuários - Perfil", "status": "skipped", "start": 1743784796436, "stop": 1743784796436}], "start": 1743784796350, "stop": 1743784796436, "uuid": "e67c84ad-c5a9-4c9f-844f-ec669d6b966d", "historyId": "decee6f137a95e1aaec409ffb75b4692", "fullName": "Acessar a página de login e testar fluxo de tela de usuários: Cancelar exclusão de um usuário", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Acessar a página de login e testar fluxo de tela de usuários"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}