{"uid":"23a19ed881365ec","name":"Usuário autenticado e associado ao perfil","fullName":"Validação de Usuário: Usuário autenticado e associado ao perfil","historyId":"52f160ff65549f9decdc744885d8065f","time":{"start":1747769537386,"stop":1747769537666,"duration":280},"status":"broken","statusMessage":"TypeError: TelaCadastroUsuarioPage.validar_usuario_cadastrado() missing 1 required positional argument: 'context'\n","statusTrace":"  File \"C:\\Users\\mferreio\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\mferreio\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\test_tela_cadastro_usuario_steps.py\", line 37, in step_usuario_foi_cadastrado\n    page.validar_usuario_cadastrado()\n","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"TypeError: TelaCadastroUsuarioPage.validar_usuario_cadastrado() missing 1 required positional argument: 'context'\n","statusTrace":"  File \"C:\\Users\\mferreio\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\mferreio\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\test_tela_cadastro_usuario_steps.py\", line 37, in step_usuario_foi_cadastrado\n    page.validar_usuario_cadastrado()\n","steps":[{"name":"Given que o usuário está logado no sistema","time":{"start":1747769537387,"stop":1747769537530,"duration":143},"status":"passed","steps":[],"attachments":[],"parameters":[],"hasContent":false,"stepsCount":0,"attachmentStep":false,"attachmentsCount":0,"shouldDisplayMessage":false},{"name":"Given que o usuário foi cadastrado no sistema","time":{"start":1747769537530,"stop":1747769537665,"duration":135},"status":"broken","statusMessage":"TypeError: TelaCadastroUsuarioPage.validar_usuario_cadastrado() missing 1 required positional argument: 'context'\n","statusTrace":"  File \"C:\\Users\\mferreio\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\mferreio\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\test_tela_cadastro_usuario_steps.py\", line 37, in step_usuario_foi_cadastrado\n    page.validar_usuario_cadastrado()\n","steps":[],"attachments":[],"parameters":[],"hasContent":true,"stepsCount":0,"attachmentStep":false,"attachmentsCount":0,"shouldDisplayMessage":true},{"name":"Then o usuário deve ser exibido na tela de usuários","time":{"start":1747769537666,"stop":1747769537666,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"hasContent":false,"stepsCount":0,"attachmentStep":false,"attachmentsCount":0,"shouldDisplayMessage":false}],"attachments":[],"parameters":[],"hasContent":true,"stepsCount":3,"attachmentStep":false,"attachmentsCount":0,"shouldDisplayMessage":false},"afterStages":[],"labels":[{"name":"severity","value":"normal"},{"name":"feature","value":"Validação de Usuário"},{"name":"framework","value":"behave"},{"name":"language","value":"cpython3"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[]}],"tags":[]},"source":"23a19ed881365ec.json","parameterValues":[]}